version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: seu_banco
      POSTGRES_USER: seu_user
      POSTGRES_DB: senha_seu_user
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
