version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: junior
      MYSQL_DATABASE: vollmed_api
      MYSQL_USER: user
      MYSQL_PASSWORD: junior
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


